// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buuhggmwaqceqzzbfwxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1dWhnZ213YXFjZXF6emJmd3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MjY4NjUsImV4cCI6MjA4NTEwMjg2NX0.FEwnKACYNzJ58pg18aO7Xs2Ev8sVSMx87adkOYUB0Ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});